[general]
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 0.95

[font]
size = 25.0

[font.bold]
family = "JetBrainsMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono"
style = "Italic"

[font.normal]
family = "JetBrainsMono"
style = "Regular"
